name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: 'News'
    labels:
      - 'enhancement'
      - 'feature'
  - title: 'Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: 'Security'
    labels:
      - 'security'
  - title: 'Maintenance'
    labels:
      - 'cleaning'
  - title: 'Docs'
    labels:
      - 'documentation'
      - 'docs'
  - title: 'Development'
    labels:
      - 'ci'
      - 'cd'
      - 'development'
  - title: 'Service bumps'
    labels:
      - 'javascript'
      - 'python'
      - 'python:uv'
  - title: 'Pipeline bumps'
    labels:
      - 'github_actions'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor
template: |
  $CHANGES
