name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: 'New things'
    labels:
      - 'enhancement'
      - 'feature'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: 'Maintenance'
    labels:
      - 'cleaning'
  - title: 'Documentation'
    labels:
      - 'documentation'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor
template: |
  # Changes

  $CHANGES
