services:
  finance-tracker:
    container_name: finance-tracker
    image: finance-tracker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./config:/app/config
      - ./load_data:/app/load_data
