name: Snyk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Snyk

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Snyk
        uses: snyk/actions/python@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
